create or replace view tweets_timeline as
select 
    j.jd.id_str     ,
    j.jd.text ,
    j.jd.created_at ,
    j.jd.coordinates ,
    j.jd.entities.hashtags.text hast_tags,
    j.jd.entities.urls.expanded_url url_in_msg ,
    j.jd.entities.user_mentions.screen_name mention_user_handles,
    j.jd.entities.user_mentions.id_str mentioned_user_ids,
    j.jd.favorite_count ,
    json_value(jd , '$.user.screen_name') user_handle ,
    json_value(jd , '$.user.name') user_name, 
    j.jd.in_reply_to_screen_name ,
    j.jd.in_reply_to_status_id_str ,
    j.jd.in_reply_to_user_id ,
    j.jd.in_reply_to_user_id_str ,
    j.jd.lang ,
    j.jd.place ,
    j.jd.quoted_status_id_str ,
    json_value(jd , '$.quoted_status.user.screen_name') quoted_user_handle,
    json_value(jd , '$.quoted_status.user.id_str') quoted_user_id,
    j.jd.quoted_status.text quoted_text,
    j.jd.retweet_count ,
    json_value(jd , '$.retweeted_status.user.screen_name') retwtd_handle,
    json_value(jd , '$.retweeted_status.user.id_str') retwtd_user_id,
    j.jd.retweeted_status.id_str retwt_id,
    j.jd.retweeted_status.text retwt_txt 
from twitter_timeline j;
